### ISSUE TITLE
Getting an error if there is no profile in aws/credentials

### ISSUE THREAD

**Issue by Arattian** [93v/dynamodb-clerk#197]
**Steps to reproduce:** 
1. Make sure you have not any profile in ~/.aws/credentials.
2. Choose "backup from remote" option.
3. Enter the configs manually.

**Comment by gevorggalstyan** [comment]
Thank you @Arattian , the issue should have been fixed already in https://github.com/93v/dynamodb-clerk/releases/tag/v2.6.9
